import { Request, Response } from 'express';
import { z } from 'zod';
import pool from '../lib/db';

// 1. Updated Schema to match the "configuration" nesting
const WorkspaceConfigSchema = z.object({
  workspace_name: z.string().min(2),
  configuration: z.object({
    primary_label: z.string().min(1),
    status_label: z.string().min(1),
    status_options: z.array(z.string().min(1)).min(1),
    current_stage: z.string().optional()
  })
});

export const createWorkspaceConfig = async (req: Request, res: Response) => {
  try {
    // 2. This will now pass because it expects the "configuration" key
    const validatedData = WorkspaceConfigSchema.parse(req.body);

    // 3. Insert the Workspace (ID is auto-generated by DB)
    const wsResult = await pool.query(
      'INSERT INTO workspaces (workspace_name) VALUES ($1) RETURNING id',
      [validatedData.workspace_name]
    );
    const newWorkspaceId = wsResult.rows[0].id;

    // 4. Insert the Configuration using the nested data
    await pool.query(
      `INSERT INTO workspace_configs 
      (workspace_id, primary_label, status_label, status_options) 
      VALUES ($1, $2, $3, $4)`,
      [
        newWorkspaceId, 
        validatedData.configuration.primary_label, // Accessed via .configuration
        validatedData.configuration.status_label,  // Accessed via .configuration
        JSON.stringify(validatedData.configuration.status_options)
      ]
    );

    return res.status(201).json({ 
      success: true, 
      workspace_id: newWorkspaceId 
    });

  } catch (error: any) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({
        error: "Validation Failed",
        // This will show you exactly which nested field is the problem
        details: error.flatten().fieldErrors 
      });
    }
    console.error("Error:", error);
    return res.status(500).json({ error: "Internal Server Error" });
  }
};